In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import scipy.stats as stats
import pycountry

In [2]:
whr_2015 = pd.read_csv("../Resources/WHR_2015.csv")
whr_2016 = pd.read_csv("../Resources/WHR_2016.csv")
whr_2017 = pd.read_csv("../Resources/WHR_2017.csv")
suicide = pd.read_csv("../Resources/who_suicide_statistics.csv")
remit_inflow = pd.read_csv("../Resources/remittance-inflow.csv")
remit_outflow = pd.read_csv("../Resources/remittance-outflow.csv")
hfi = pd.read_csv("../Resources/hfi_cc_2018.csv")
efw = pd.read_csv("../Resources/efw_cc.csv")
bilat_remit = pd.read_csv("../Resources/bilateral-remittance.csv")

In [3]:
##Column Diffs
#'Standard Error' - Will Delete; Only in WHR 2015


##Column Names that need to be standardized - All WHR 2017
#'Happiness.Score' -> 'Happiness Score'
#'Whisker.high' -> 'Upper Confidence Interval'
#'Whisker.low' -> 'Lower Confidence Interval'
#'Happiness.Rank' -> 'Happiness Rank'
#'Economy..GDP.per.Capita.' -> 'Economy (GDP per Capita)'
#'Health..Life.Expectancy.' -> 'Health (Life Expectancy)'
#'Dystopia.Residual' -> 'Dystopia Residual'
#'Trust..Government.Corruption.' -> 'Trust (Government Corruption)'

In [4]:
#ensure we have same columns and columns names
whr_2015.columns

Index(['Country', 'Region', 'Happiness Rank', 'Happiness Score',
       'Standard Error', 'Economy (GDP per Capita)', 'Family',
       'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)',
       'Generosity', 'Dystopia Residual'],
      dtype='object')

In [5]:
#Dropped Standard Error and Region columns, as it's not in 2016/17 
whr_2015 = whr_2015.drop(columns='Standard Error')
whr_2015 = whr_2015.drop(columns='Region')

In [6]:
whr_2015.head(2)

,Country,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Switzerland,1,7.587,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,2,7.561,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201

In [7]:
#Dropped L/U Conf Interval and Region Columns
whr_2016.columns
whr_2016 = whr_2016.drop(['Lower Confidence Interval','Upper Confidence Interval'], axis=1)
whr_2016 = whr_2016.drop(columns='Region')

In [8]:
whr_2016.head(2)

,Country,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Denmark,1,7.526,1.44178,1.16374,0.79504,0.57941,0.44453,0.36171,2.73939
1,Switzerland,2,7.509,1.52733,1.14524,0.86303,0.58557,0.41203,0.28083,2.69463

In [9]:
#Dropped L/U Conf Interval and Region Columns
whr_2017.columns
whr_2017 = whr_2017.drop(['Lower Confidence Interval','Upper Confidence Interval'], axis=1)

KeyError: "['Lower Confidence Interval' 'Upper Confidence Interval'] not found in axis"

In [10]:
# Rename multiple columns in one go with a larger dictionary
#'Happiness.Score' -> 'Happiness Score'
#'Whisker.high' -> 'Upper Confidence Interval'
#'Whisker.low' -> 'Lower Confidence Interval'
#'Happiness.Rank' -> 'Happiness Rank'
#'Economy..GDP.per.Capita.' -> 'Economy (GDP per Capita)'
#'Health..Life.Expectancy.' -> 'Health (Life Expectancy)'
#'Dystopia.Residual' -> 'Dystopia Residual'
#'Trust..Government.Corruption.' -> 'Trust (Government Corruption)'

whr_2017.rename(
    columns={
        "Happiness.Score": "Happiness Score",
        "Whisker.high": "Upper Confidence Interval",
        "Whisker.low": "Lower Confidence Interval",
        "Happiness.Rank": "Happiness Rank",
        "Economy..GDP.per.Capita.": "Economy (GDP per Capita)",
        "Health..Life.Expectancy.": "Health (Life Expectancy)",
        "Dystopia.Residual": "Dystopia Residual",
        "Trust..Government.Corruption.": "Trust (Government Corruption)",
    },
    inplace=True)

In [11]:
whr_2017.head(2)

,Country,Happiness Rank,Happiness Score,Upper Confidence Interval,Lower Confidence Interval,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Generosity,Trust (Government Corruption),Dystopia Residual
0,Norway,1,7.537,7.594445,7.479556,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027
1,Denmark,2,7.522,7.581728,7.462272,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707

In [12]:
#Happiness Reports are missing years. Adding Year column with set year values before merge
whr_2015['Year']='2015'
whr_2016['Year']='2016'
whr_2017['Year']='2017'

In [13]:
whr_2016.head()

,Country,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual,Year
0,Denmark,1,7.526,1.44178,1.16374,0.79504,0.57941,0.44453,0.36171,2.73939,2016
1,Switzerland,2,7.509,1.52733,1.14524,0.86303,0.58557,0.41203,0.28083,2.69463,2016
2,Iceland,3,7.501,1.42666,1.18326,0.86733,0.56624,0.14975,0.47678,2.83137,2016
3,Norway,4,7.498,1.57744,1.12690,0.79579,0.59609,0.35776,0.37895,2.66465,2016
4,Finland,5,7.413,1.40598,1.13464,0.81091,0.57104,0.41004,0.25492,2.82596,2016

In [14]:
#merge world happiness reports
whr_frames = [whr_2015, whr_2016, whr_2017]
merged_whr = pd.concat(whr_frames, sort=False)

In [15]:
merged_whr.head()

,Country,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual,Year,Upper Confidence Interval,Lower Confidence Interval
0,Switzerland,1,7.587,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738,2015,NaN,NaN
1,Iceland,2,7.561,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201,2015,NaN,NaN
2,Denmark,3,7.527,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204,2015,NaN,NaN
3,Norway,4,7.522,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531,2015,NaN,NaN
4,Canada,5,7.427,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176,2015,NaN,NaN

In [16]:
merged_whr.sort_values(['Year', "Happiness Score"], ascending=[True, False], inplace=True)

In [17]:
merged_whr

,Country,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual,Year,Upper Confidence Interval,Lower Confidence Interval
0,Switzerland,1,7.587,1.396510,1.349510,0.941430,0.665570,0.419780,0.296780,2.517380,2015,NaN,NaN
1,Iceland,2,7.561,1.302320,1.402230,0.947840,0.628770,0.141450,0.436300,2.702010,2015,NaN,NaN
2,Denmark,3,7.527,1.325480,1.360580,0.874640,0.649380,0.483570,0.341390,2.492040,2015,NaN,NaN
3,Norway,4,7.522,1.459000,1.330950,0.885210,0.669730,0.365030,0.346990,2.465310,2015,NaN,NaN
4,Canada,5,7.427,1.326290,1.322610,0.905630,0.632970,0.329570,0.458110,2.451760,2015,NaN,NaN
5,Finland,6,7.406,1.290250,1.318260,0.889110,0.641690,0.413720,0.233510,2.619550,2015,NaN,NaN
6,Netherlands,7,7.378,1.329440,1.280170,0.892840,0.615760,0.318140,0.476100,2.465700,2015,NaN,NaN
7,Sweden,8,7.364,1.331710,1.289070,0.910870,0.659800,0.438440,0.362620,2.371190,2015,NaN,NaN
8,New Zealand,9,7.286,1.250180,1.319670,0.908370,0.639380,0.429220,0.475010,2.264250,2015,NaN,NaN
9,Australia,10,7.284,1.333580,1.309230,0.931560,0.651240,0.356370,0.435620,2.266460,2015,NaN,NaN
10,Israel,11,7.278,1.228570,1.223930,0.913870,0.413190,0.077850,0.331720,3.088540,2015,NaN,NaN
11,Costa Rica,12,7.226,0.955780,1.237880,0.860270,0.633760,0.105830,0.254970,3.177280,2015,NaN,NaN
12,Austria,13,7.200,1.337230,1.297040,0.890420,0.624330,0.186760,0.330880,2.533200,2015,NaN,NaN
13,Mexico,14,7.187,1.020540,0.914510,0.814440,0.481810,0.213120,0.140740,3.602140,2015,NaN,NaN
14,United States,15,7.119,1.394510,1.247110,0.861790,0.546040,0.158900,0.401050,2.510110,2015,NaN,NaN
15,Brazil,16,6.983,0.981240,1.232870,0.697020,0.490490,0.175210,0.145740,3.260010,2015,NaN,NaN
16,Luxembourg,17,6.946,1.563910,1.219630,0.918940,0.615830,0.377980,0.280340,1.969610,2015,NaN,NaN
17,Ireland,18,6.940,1.335960,1.369480,0.895330,0.617770,0.287030,0.459010,1.975700,2015,NaN,NaN
18,Belgium,19,6.937,1.307820,1.285660,0.896670,0.584500,0.225400,0.222500,2.414840,2015,NaN,NaN
19,United Arab Emirates,20,6.901,1.427270,1.125750,0.809250,0.641570,0.385830,0.264280,2.247430,2015,NaN,NaN
20,United Kingdom,21,6.867,1.266370,1.285480,0.909430,0.596250,0.320670,0.519120,1.969940,2015,NaN,NaN
21,Oman,22,6.853,1.360110,1.081820,0.762760,0.632740,0.325240,0.215420,2.474890,2015,NaN,NaN
22,Venezuela,23,6.810,1.044240,1.255960,0.720520,0.429080,0.110690,0.058410,3.191310,2015,NaN,NaN
23,Singapore,24,6.798,1.521860,1.020000,1.025250,0.542520,0.492100,0.311050,1.885010,2015,NaN,NaN
24,Panama,25,6.786,1.063530,1.198500,0.796610,0.542100,0.092700,0.244340,2.848480,2015,NaN,NaN
25,Germany,26,6.750,1.327920,1.299370,0.891860,0.614770,0.218430,0.282140,2.115690,2015,NaN,NaN
26,Chile,27,6.670,1.107150,1.124470,0.858570,0.441320,0.128690,0.333630,2.675850,2015,NaN,NaN
27,Qatar,28,6.611,1.690420,1.078600,0.797330,0.640400,0.522080,0.325730,1.556740,2015,NaN,NaN
28,France,29,6.575,1.277780,1.260380,0.945790,0.550110,0.206460,0.123320,2.211260,2015,NaN,NaN
29,Argentina,30,6.574,1.053510,1.248230,0.787230,0.449740,0.084840,0.114510,2.836000,2015,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,Congo (Kinshasa),126,4.280,0.092102,1.229023,0.191407,0.235961,0.060241,0.246456,2.224959,2017,4.357811,4.202190
126,Mali,127,4.190,0.476180,1.281473,0.169366,0.306614,0.104970,0.183354,1.668191,2017,4.269671,4.110329
127,Ivory Coast,128,4.180,0.603049,0.904780,0.048642,0.447706,0.130062,0.201237,1.844964,2017,4.275183,4.084817
128,Cambodia,129,4.168,0.601765,1.006238,0.429783,0.633376,0.068106,0.385923,1.042941,2017,4.278518,4.057483
129,Sudan,130,4.139,0.659517,1.214009,0.290921,0.014996,0.089848,0.182317,1.687066,2017,4.345747,3.932253
130,Ghana,131,4.120,0.667225,0.873665,0.295638,0.423026,0.025336,0.256924,1.577868,2017,4.222707,4.017293
131,Ukraine,132,4.096,0.894652,1.394538,0.575904,0.122975,0.023029,0.270061,0.814382,2017,4.185410,4.006590
132,Uganda,133,4.081,0.381431,1.129828,0.217633,0.443186,0.057070,0.325766,1.526363,2017,4.195800,3.966200
133,Burkina Faso,134,4.032,0.350228,1.043280,0.215844,0.324368,0.120328,0.250865,1.727213,2017,4.124059,3.939941
134,Niger,135,4.028,0.161925,0.993025,0.268505,0.363659,0.138573,0.228674,1.873983,2017,4.111947,3.944053
135,Malawi,136,3.970,0.233442,0.512569,0.315090,0.466915,0.072712,0.287170,2.081786,2017,4.077479,3.862521
136,Chad,137,3.936,0.438013,0.953856,0.041135,0.162342,0.053582,0.216114,2.071238,2017,4.034712,3.837289
137,Zimbabwe,138,3.875,0.375847,1.083096,0.196764,0.336384,0.095375,0.189143,1.597970,2017,3.978700,3.771300
138,Lesotho,139,3.808,0.521021,1.190095,0.000000,0.390661,0.119095,0.157497,1.429835,2017,4.044344,3.571656
139,Angola,140,3.795,0.858428,1.104412,0.049869,0.000000,0.069720,0.097926,1.614482,2017,3.951642,3.638358
140,Afghanistan,141,3.794,0.401477,0.581543,0.180747,0.106180,0.061158,0.311871,2.150801,2017,3.873661,3.714338
141,Botswana,142,3.766,1.122094,1.221555,0.341756,0.505196,0.098583,0.099348,0.377914,2017,3.874123,3.657877
142,Benin,143,3.657,0.431085,0.435300,0.209930,0.425963,0.060929,0.207948,1.885631,2017,3.745784,3.568217
143,Madagascar,144,3.644,0.305809,0.913020,0.375223,0.189197,0.067232,0.208733,1.584613,2017,3.714319,3.573681
144,Haiti,145,3.603,0.368610,0.640450,0.277321,0.030370,0.099872,0.489204,1.697168,2017,3.734715,3.471285
145,Yemen,146,3.593,0.591683,0.935382,0.310081,0.249464,0.056767,0.104125,1.345601,2017,3.692750,3.493250
146,South Sudan,147,3.591,0.397249,0.601323,0.163486,0.147062,0.116794,0.285671,1.879567,2017,3.725539,3.456462
147,Liberia,148,3.533,0.119042,0.872118,0.229918,0.332881,0.038948,0.266550,1.673286,2017,3.653756,3.412244
148,Guinea,149,3.507,0.244550,0.791245,0.194129,0.348588,0.110938,0.264815,1.552312,2017,3.584428,3.429572
149,Togo,150,3.495,0.305445,0.431883,0.247106,0.380426,0.095665,0.196896,1.837229,2017,3.594038,3.395962
150,Rwanda,151,3.471,0.368746,0.945707,0.326425,0.581844,0.455220,0.252756,0.540061,2017,3.543030,3.398970
151,Syria,152,3.462,0.777153,0.396103,0.500533,0.081539,0.151347,0.493664,1.061574,2017,3.663669,3.260331
152,Tanzania,153,3.349,0.511136,1.041990,0.364509,0.390018,0.066035,0.354256,0.621130,2017,3.461430,3.236570
153,Burundi,154,2.905,0.091623,0.629794,0.151611,0.059901,0.084148,0.204435,1.683024,2017,3.074690,2.735310
154,Central African Republic,155,2.693,0.000000,0.000000,0.018773,0.270842,0.056565,0.280876,2.066005,2017,2.864884,2.521116

In [18]:
for i, row in merged_whr.iterrows():
   try:
       merged_whr.loc[i, 'country code'] = pycountry.countries.lookup(row['Country']).alpha_3
   except LookupError:
       merged_whr.loc[i, 'country code'] = '*unk'
       #print(row['Country'])
    
merged_whr.to_csv("../Resources/whr_combined_cleaned.csv", index=False)

In [19]:
for i, row in whr_2015.iterrows():
   try:
       whr_2015.loc[i, 'country code'] = pycountry.countries.lookup(row['Country']).alpha_3
   except LookupError:
       whr_2015.loc[i, 'country code'] = '*unk'

whr_2015.to_csv("../Resources/whr_2015_cleaned.csv", index=False)

In [20]:
for i, row in whr_2016.iterrows():
   try:
       whr_2016.loc[i, 'country code'] = pycountry.countries.lookup(row['Country']).alpha_3
   except LookupError:
       whr_2016.loc[i, 'country code'] = '*unk'
        
whr_2016.to_csv("../Resources/whr_2016_cleaned.csv", index=False)

In [21]:
for i, row in whr_2017.iterrows():
   try:
       whr_2017.loc[i, 'country code'] = pycountry.countries.lookup(row['Country']).alpha_3
   except LookupError:
       whr_2017.loc[i, 'country code'] = '*unk'

whr_2017.to_csv("../Resources/whr_2017_cleaned.csv", index=False)